Repository airavata-courses/scapsulators, pull requests merged in 2022-02, with the labels that each got.

#43 feature update for gateway #42
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  Documentation/UI-Napkin-Diagrams/Readme.md
  gateway/docker-compose.yml
Labels: Backend

#60 Project1 release
  Documentation/Team-members/Rutuja.jpg
  Documentation/Team-members/Vikrant.jpg
  Documentation/UI-Napkin-Diagrams/Temp.drawio
  README.md
  docker-compose.yml
  start-Weatherpedia.sh
Labels: documentation, CICD, Connectivity

#57 Development gateway circle ci feature
  .circleci/config.yml
  .travis.yml
  Documentation/Microservices-Overview/Integration test cases.png
  gateway/.dockerignore
  gateway/.env
  gateway/Dockerfile
  gateway/Makefile
  gateway/controllers/audit.js
  gateway/controllers/authenticate.js
  gateway/controllers/weather.js
  gateway/coverage/clover.xml
  gateway/coverage/coverage-final.json
  gateway/coverage/lcov-report/base.css
  gateway/coverage/lcov-report/block-navigation.js
  gateway/coverage/lcov-report/favicon.png
  gateway/coverage/lcov-report/index.html
  gateway/coverage/lcov-report/prettify.css
  gateway/coverage/lcov-report/prettify.js
  gateway/coverage/lcov-report/sort-arrow-sprite.png
  gateway/coverage/lcov-report/sorter.js
  gateway/coverage/lcov.info
  gateway/helpers/encrypt.js
  gateway/package-lock.json
  gateway/package.json
  gateway/routes/allRoute.js
  gateway/server.js
  gateway/temp/mimic.js
  gateway/tests/audit.test.js
  gateway/tests/auth.test.js
  gateway/tests/weather.test.js
Labels: Backend, CICD
